
import "./globals.css";



export const metadata = {
  title: "Week2 classwork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <main> {children}</main>
       <footer className="footer">Footer</footer>
      </body>
    </html>
  );
}
