import "./globals.css";
import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/Footer";


export const metadata = {
  title: "Week2 classwork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main style={{ paddingTop: "60px", paddingBottom: "40px" }}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
